---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgweb
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
spec:
  ingressClassName: nginx
  rules:
  - host: pgweb.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pgweb
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pgweb
  labels:
    app: pgweb
spec:
  type: ClusterIP
  ports:
  - name: pgweb
    port: 80
    targetPort: 8081
  selector:
    app: pgweb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb
  labels:
    app: pgweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgweb
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      containers:
      - name: pgweb
        image: sosedoff/pgweb:0.11.11
